CREATE USER "SECUREFLOW_DB_USER" WITH PASSWORD 'SECUREFLOW_DB_PASSWD_TO_CHANGE';
CREATE DATABASE "patrowl_db" WITH OWNER "SECUREFLOW_DB_USER";
ALTER ROLE "SECUREFLOW_DB_USER" SET client_encoding TO 'utf8';
ALTER ROLE "SECUREFLOW_DB_USER" SET default_transaction_isolation TO 'read committed';
-- ALTER ROLE "SECUREFLOW_DB_USER" SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE "patrowl_db" TO "SECUREFLOW_DB_USER";
