ALTER ROLE "SECUREFLOW_DB_USER" SET client_encoding TO 'utf8';
ALTER ROLE "SECUREFLOW_DB_USER" SET default_transaction_isolation TO 'read committed';
ALTER ROLE "SECUREFLOW_DB_USER" SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE "patrowl_db" TO "SECUREFLOW_DB_USER";
